#!/bin/sh
#
# ██                                                           
#░██              ██████                                       
#░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████ 
#░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
#░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░ 
#░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
#░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████ 
#░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░  

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {$(echo -e '\uf120'),$(echo -e '\uf269'),$(echo -e '\uf121'),$(echo -e '\uf07b'),$(echo -e '\uf099'),$(echo -e '\uf1bc'),$(echo -e '\uf11b')}
    let i++
done
NMON=$i
unset i

# Visual options
bspc config top_padding 20
bspc config border_width 4
bspc config window_gap 16
bspc config normal_border_color "#2b303b"
bspc config active_border_color "#2b303b"
bspc config focused_border_color "#8fa1b3"
bspc config presel_feedback_color "#96b5b4"
bspc config focused_locked_border_color "#b48ead"

# Behavior
bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_follows_pointer true
bspc config initial_polarity first_child

# Pointer options
bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner


# Setting default layouts for desktops
bspc desktop ^2 -l monocle
bspc desktop ^3 -l monocle

# Rules
bspc rule -a Firefox desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a chromium desktop='^2'
bspc rule -a Atom desktop='^3'
bspc rule -a Emacs desktop='^3'
bspc rule -a Thunar desktop='^4'
bspc rule -a Filezilla desktop='^4'
bspc rule -a Gimp desktop='^4'
bspc rule -a Inkscape desktop='^4'
bspc rule -a Pcmanfm desktop='^4'
bspc rule -a Blender desktop='^4' state=pseudo_tiled
bspc rule -a File-roller state=pseudo_tiled
bspc rule -a Transmission-gtk desktop='^4'
bspc rule -a astime flag=sticky
bspc rule -a MPlayer state=floating
bspc rule -a Steam desktop='^7'

# Placing CLI apps on desktops
bspc rule -a URxvt:vim desktop='^3'
bspc rule -a URxvt:mutt desktop='^4'
bspc rule -a URxvt:vifm desktop='^4'
bspc rule -a URxvt:ranger desktop='^4'
bspc rule -a URxvt:irssi desktop='^5'
bspc rule -a URxvt:rainbowstream desktop='^5'
bspc rule -a URxvt:twitter desktop='^5'
bspc rule -a URxvt:ncmpcpp desktop='^6'

#/home/jorick/.config/bspwm/panel/panel &
panel &

# scrit to automatically adjust the gaps depending on number of windows
#bspwm_auto_gap.sh &
