#! /bin/bash

./.xinit.d/background &
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
sxhkd &
urxvtd -q -o -f &
udiskie -T &
#setxkbmap "be" &
compton -c -r 8 -o 0.70 -l -5 -t -5 -b &
mopidy &
xsetroot -cursor_name left_ptr &
dunst &

exec bspwm
